apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-workflows
  namespace: advtech
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: argo
  project: default
  source:
    path: eks/argocd/argo-workflows/overlays/local
    repoURL: git@github.com:ACSPubsEDSG/OR_edsg_gitops.git
    targetRevision: HEAD
  syncPolicy: 
    syncOptions:
    - CreateNamespace=true

    automated: 
      prune: true
      selfHeal: true
