apiVersion: v1
kind: ConfigMap
metadata:
  name: at-ai-att-fe-ui-configmap
  namespace: advtech
data:
  sso.properties: |
    env=dev
    appid=AIATTGCP
    scope=role email constituentid acsid firstname lastname groups divisions source products offer roles
    protectedPaths=/transfer
    cancelurl=https://javiasdev.gcp.acs.org/transfer/home
    continueLabel=Back to AIATT
    default_max_age=30
    redirecturl=https://javiasdev.gcp.acs.org/transfer/home/redirect