apiVersion: v1
kind: ConfigMap
metadata:
  name: rrcc-configmap
  namespace: advtech
data:
  config.ini: |
    #redis-stag
    #NodeAddress = 172.23.30.141:6379,172.23.30.142:6379,172.23.30.143:6379,172.23.30.144:6379,172.23.30.145:6379,172.23.30.146:6379
    #password = redistest
    #prefixForSortedSet = rc:topn:1:1:
    #prefixForHashes = rc:metadata:

    #NodeAddress = 172.23.40.135:6379,172.23.40.136:6379,172.23.40.137:6379
    NodeAddress = dev-lnx-3062.acs.org:6379,dev-lnx-3063.acs.org:6379,dev-lnx-3064.acs.org:6379
    password = redisdev
    prefixForRecommendation = rc:topn
    prefixForHistory = rc:hist
    version = 1
    iteration = 1
