apiVersion: batch/v1
kind: CronJob
metadata:
  name: at-ai-att-fe-training-trnsfrcnnjob
  namespace: advtech
spec:
  schedule: "50 10 * * *"
  concurrencyPolicy: Replace
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: at-ai-att-fe-training-trnsfrcnnjob
            image: ghcr.io/acspubsedsg/ai-att-training-be:latest
            imagePullPolicy: Always
            resources:
              requests:
                cpu: 2000m 
                memory: 2048Mi
              limits:
                cpu: 4000m 
                memory: 4096Mi
            command:
            - /bin/sh
            - -c
            - mkdir -p /NAS/AIMODELS/manuscript-transfer-cnn/model && mv config/manuscript-transfer-cnn_dev.ini config/manuscript-transfer-cnn.ini && conda run --name manuscript-transfer-cnn python -u cnn_gensim.py
            volumeMounts:
            - name: filestore 
              mountPath: /NAS
          nodeSelector:
            mark: gputest
          imagePullSecrets:
          - name: ghcr-token-github-com
          volumes:
          - name: filestore
            persistentVolumeClaim:
              claimName: filestore-nfs-pvc
              readOnly: false
          restartPolicy: OnFailure