apiVersion: apps/v1
kind: Deployment
metadata:
  name: at-ai-arr-fe-ui
  namespace: advtech
spec:
  replicas: 1
  selector:
    matchLabels:
      app: at-ai-arr-fe-ui
  template:
    metadata:
      labels:
        app: at-ai-arr-fe-ui
    spec:
      containers:
      - name: at-ai-arr-fe-ui
        image: ghcr.io/acspubsedsg/at-ai-arr-fe-ui:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: dev
        resources:
          requests:
            cpu: 1000m 
            memory: 2048Mi
          limits:
            cpu: 1500m 
            memory: 3072Mi
        volumeMounts:
        - mountPath: /appl/iapps/ssoProperties/
          name: at-ai-arr-fe-ui-config-volume
      volumes:
        - name: at-ai-arr-fe-ui-config-volume
          configMap:
            name: at-ai-arr-fe-ui-configmap
      imagePullSecrets:
        - name: ghcr-token-github-com
        