apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: at-ai-tool-dashboard-ingress
  namespace: advtech
  annotations:
    ingress.gcp.kubernetes.io/pre-shared-cert: "javiasdev-gcp-acs-org"
    kubernetes.io/ingress.class: "gce-internal"
    kubernetes.io/ingress.regional-static-ip-name: "at-ai-tool-dashboard-static-ip-dev"
    networking.gke.io/suppress-firewall-xpn-error: "true"
    kubernetes.io/ingress.allow-http: "false"
spec:
  rules:
    - http:
        paths:
#          - path: /Dashboard/*
#            pathType: ImplementationSpecific
#            backend:
#              service:
#                name: at-ai-tool-dashboard
#                port:
#                  number: 8080
#          - path: /transfer/*
#            pathType: ImplementationSpecific
#            backend:
#              service:
#                name: at-ai-att-fe-ui
#                port:
#                  number: 8080
#          - path: /reviewers/*
#            pathType: ImplementationSpecific
#            backend:
#              service:
#                name: at-ai-arr-fe-ui
#                port:
#                  number: 8080
#          - path: /editors/*
#            pathType: ImplementationSpecific
#            backend:
#              service:
#                name: at-ai-aer-fe-ui
#                port:
#                  number: 8080
#          - path: /originality/*
#            pathType: ImplementationSpecific
#            backend:
#              service:
#                name: at-ai-aoe-fe-ui
#                port:
#                  number: 8080
          - path: /mta_api/v1/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: at-ai-mta-fe-api
                port:
                  number: 8080
          - path: /topicanalyzer/*
            pathType: ImplementationSpecific
            backend:
              service:
                name: at-ai-mta-fe-ui
                port:
                  number: 8080
  defaultBackend:
    service:
      name: at-ai-mta-fe-ui
      port:
        number: 8080
