apiVersion: v1
data:
    .dockerconfigjson: eyJhdXRocyI6eyJnaGNyLmlvIjp7ImF1dGgiOiJNakV3TVdKb1lYVjBhV3M2WjJod1h6bG5jRWRPTm1KYVprTnlaalJ0VUZZNFduYzVZVTAzTW5ZeFlrdDRNelJsZEdKS01RPT0ifX19
kind: Secret
metadata:
    name: ghcr-token-github-com
    namespace: advtech
type: kubernetes.io/dockerconfigjson
