apiVersion: v1
kind: Service
metadata:
  name: at-ai-aer-jacs-fe-inferencing-predict-manuscript
  namespace: advtech
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
  labels:
    app: at-ai-aer-jacs-fe-inferencing-predict-manuscript
spec:
  type: ClusterIP
  ports:
    - port: 5006
      targetPort: 5006
      protocol: TCP
      name: http
  selector:
    app: at-ai-aer-jacs-fe-inferencing-predict-manuscript
    