apiVersion: v1
kind: ConfigMap
metadata:
  name: secret-server-configmap
  namespace: advtech
data:
  secret-server.ini: |
    [info]
    url=https://acs.secretservercloud.com/
    accessTokenUrl=https://acs.secretservercloud.com/oauth2/token
    rootApiUrl=https://acs.secretservercloud.com/api/v1/secrets
    domain=
    grant_type=password
    username=sdk-edsg-prod-aitools
    password=new8Dudr4Y#ThowwR6Im