apiVersion: batch/v1
kind: CronJob
metadata:
  name: cronjob-aiarr-fe-inferencing-curl-on-cron
  namespace: advtech
spec:
  schedule: "*/2 * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: curlimage
              image: curlimages/curl
              imagePullPolicy: IfNotPresent
              resources:
                requests:
                  memory: "200Mi"
                  cpu: "700m"
                limits:
                  memory: "200Mi"
                  cpu: "700m"
              command:
                - /bin/sh
                - -c
              args:
                - curl -s 'http://at-ai-arr-fe-inferencing:5003/manuscript-reviewer/process-s1'
          restartPolicy: OnFailure