apiVersion: batch/v1
kind: CronJob
metadata:
  name: at-ai-aer-fe-inferencing-restart-jacs
  namespace: advtech
spec:
  timeZone: "EST"
  schedule: "0 18 * * 6"
  concurrencyPolicy: Replace
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 2
      activeDeadlineSeconds: 600
      template:
        spec:
          serviceAccountName: restart-deployment
          restartPolicy: Never
          containers:
            - name: kubectl
              image: bitnami/kubectl
              command:
                - bash
                - -c
                - >-
                  kubectl rollout restart deployment/at-ai-aer-jacs-fe-inferencing-predict-manuscript &&
                  kubectl rollout status deployment/at-ai-aer-jacs-fe-inferencing-predict-manuscript &&
                  kubectl rollout restart deployment/at-ai-aer-jacs-fe-inferencing-realtime-topn &&
                  kubectl rollout status deployment/at-ai-aer-jacs-fe-inferencing-realtime-topn