apiVersion: apps/v1
kind: Deployment
metadata:
  name: at-ai-aer-fe-api
  namespace: advtech
spec:
  replicas: 1
  selector:
    matchLabels:
      app: at-ai-aer-fe-api
  template:
    metadata:
      labels:
        app: at-ai-aer-fe-api
    spec:
      containers:
      - name: at-ai-aer-fe-api
        image: ghcr.io/acspubsedsg/at-ai-aer-fe-api:prod
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: prod
        - name: TZ
          value: EST
        - name: SPRING_DATASOURCE_URL
          value: "jdbc:oracle:thin:@(DESCRIPTION=(FAILOVER=on)(LOAD_BALANCE=no)(ADDRESS=(PROTOCOL=TCP)(HOST=prod-lnx-3403.acs.org)(PORT=1521))(CONNECT_DATA=(SERVICE_NAME=mspubs.acs.org)))"
        resources:
          requests:
            cpu: 1000m 
            memory: 2048Mi
          limits:
            cpu: 1500m 
            memory: 3072Mi
      imagePullSecrets:
        - name: ghcr-token-github-com  