apiVersion: apps/v1
kind: Deployment
metadata:
  name: at-ai-arr-fe-api
  namespace: advtech
spec:
  replicas: 1
  selector:
    matchLabels:
      app: at-ai-arr-fe-api
  template:
    metadata:
      labels:
        app: at-ai-arr-fe-api
    spec:
      containers:
      - name: at-ai-arr-fe-api
        image: ghcr.io/acspubsedsg/at-ai-arr-fe-api@sha256:4ab0c636d08bb668ca2b22a29a8beff232f330f72176edf03ce671b1fa7710fe
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: prod
        - name: TZ
          value: EST
        resources:
          requests:
            cpu: 1000m 
            memory: 2048Mi
          limits:
            cpu: 1500m 
            memory: 3072Mi
        volumeMounts:
        - mountPath: /appl/iapps/config/
          name: secret-server-configmap
      volumes:
        - name: secret-server-configmap
          configMap:
            name: secret-server-configmap
      imagePullSecrets:
        - name: ghcr-token-github-com  
