apiVersion: apps/v1
kind: Deployment
metadata:
  name: at-ai-s1-fe-api
  namespace: advtech
spec:
  replicas: 1
  selector:
    matchLabels:
      app: at-ai-s1-fe-api
  template:
    metadata:
      labels:
        app: at-ai-s1-fe-api
    spec:
      containers:
      - name: at-ai-s1-fe-api
        image: ghcr.io/acspubsedsg/at-ai-s1-fe-api@sha256:a3e667cce351fb184448c425805d18e02c6cf536f8d54a7ea5e18a79501d37bc
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: prod
        - name: TZ
          value: EST
        resources:
          requests:
            cpu: 1000m
            memory: 2048Mi
          limits:
            cpu: 1500m
            memory: 3072Mi
      imagePullSecrets:
        - name: ghcr-token-github-com
      restartPolicy: Always
