apiVersion: v1
kind: Service
metadata:
  name: at-ai-att-fe-inferencing
  namespace: advtech
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
  labels:
    app: at-ai-att-fe-inferencing
spec:
  type: ClusterIP
  ports:
    - port: 5002
      targetPort: 5002
      protocol: TCP
      name: http
  selector:
    app: at-ai-att-fe-inferencing