apiVersion: v1
kind: ConfigMap
metadata:
  name: at-resource-monitor-ui-configmap
  namespace: advtech
data:
  sso.properties: |
    env=test
    appid=monitor_staging
    scope=email constituentid acsid firstname lastname fullname ismember hasrenewal ispaid aactismember aacthasrenewal aactispaid groups divisions source products keepmeloggedin isrealtime oauthaccesstoken oauthrefreshtoken lastsucclogin lastfailedattemp errorcodes
    publicPaths=/css,/images,/fonts,/js
    protectedFiles=dashboard,monitors,login
    redirecturl=https://webappitest.acs.org/arm/redirect