apiVersion: v1
kind: ConfigMap
metadata:
  name: at-ai-arr-fe-ui-configmap
  namespace: advtech
data:
  sso.properties: |
    env=test
    appid=AIARRSTAG
    scope=role email constituentid acsid firstname lastname groups divisions source products offer roles
    protectedPaths=/reviewers
    cancelurl=https://javiastest.acs.org/reviewers/home
    continueLabel=Back to AIARR
    default_max_age=30
    redirecturl=https://javiastest.acs.org/reviewers/home/redirect
    returnURL=https://javiastest.acs.org/reviewers/home