apiVersion: v1
kind: ConfigMap
metadata:
  name: at-ai-admin-arr-fe-configmap
  namespace: advtech
data:
  sso.properties: |
    env=test
    appid=AIARRAdminStag
    scope=role email constituentid acsid firstname lastname groups divisions source products offer roles
    protectedPaths=/reviewers
    cancelurl=https://javiastest-admin.acs.org/reviewers/home
    continueLabel=Back to AIARR admin
    default_max_age=30
    redirecturl=https://javiastest-admin.acs.org/reviewers/home/redirect
    returnURL=https://javiastest-admin.acs.org/reviewers/home