apiVersion: v1
kind: ConfigMap
metadata:
  name: at-ai-aer-fe-ui-configmap
  namespace: advtech
data:
  sso.properties: |
    env=test
    appid=AIAERGCPSTAG
    scope=role email constituentid acsid firstname lastname groups divisions source products offer roles
    protectedPaths=/editors
    cancelurl=https://javiasdev.gcp.acs.org/editors/home
    continueLabel=Back to AIAER
    default_max_age=30
    redirecturl=https://javiasdev.gcp.acs.org/editors/home/redirect
    returnURL=https://javiastest.gcp.acs.org/editors/home