apiVersion: batch/v1
kind: CronJob
metadata:
  name: at-aiaer-s1-bidirectional-nano
  namespace: advtech
spec:
  schedule: "* * * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      activeDeadlineSeconds: 600
      template:
        spec:
          containers:
          - name: at-aiaer-s1-bidirectional-nano
            image: ghcr.io/acspubsedsg/at-aiaer-s1-bidirectional:latest
            imagePullPolicy: Always
            env:
            - name: SPRING_PROFILES_ACTIVE
              value: test
            - name: S1_BIDIRECTIONAL_PROCESS_JOURNALID
              value: "nn"
            - name: S1_BIDIRECTIONAL_PREPROCESS_SKIP-INFINITE-EXECUTION
              value: "true"
            resources:
              requests:
                cpu: 500m
                memory: 2048Mi
              limits:
                cpu: 1000m
                memory: 2048Mi
            volumeMounts:
            - mountPath: /appl/iapps/config/
              name: secret-server-configmap
          volumes:
            - name: secret-server-configmap
              configMap:
                name: secret-server-configmap
          imagePullSecrets:
            - name: ghcr-token-github-com
          restartPolicy: OnFailure
