apiVersion: batch/v1
kind: CronJob
metadata:
  name: at-ai-aoe-fe-training-aise-specter-incremental
  namespace: advtech
spec:
  timeZone: "EST"
  schedule: "30 1 * * 0"
  concurrencyPolicy: Replace
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: at-ai-aoe-fe-training-aise-specter-incremental
              image: ghcr.io/acspubsedsg/at-ai-aoe-fe-training:latest
              imagePullPolicy: Always
              env:
                - name: LD_LIBRARY_PATH
                  value: /usr/local/nvidia/lib64
              resources:
                requests:
                  cpu: 13200m
                  memory: 143Gi
                  nvidia.com/gpu: 1
                limits:
                  cpu: 15500m
                  memory: 143Gi
                  nvidia.com/gpu: 1
              command:
                - /bin/sh
                - -c
                - mkdir -p /NAS/AIMODELS/specter-stag/vector && mkdir -p /NAS/AIMODELS/specter-stag/data && mv aiamne-specter_stag.ini aiamne-specter.ini && python aise-specter-incremental.py
              volumeMounts:
                - name: filestore
                  mountPath: /NAS
                - mountPath: /usr/local/nvidia
                  name: nvidia
          tolerations:
            - key: nvidia.com/gpu
              operator: Exists
              effect: NoSchedule
            - key: enable
              operator: "Equal"
              value: "highcpugpumemory"
              effect: NoSchedule
          imagePullSecrets:
            - name: ghcr-token-github-com
          volumes:
            - name: nvidia
              hostPath:
                path: /home/kubernetes/bin/nvidia
            - name: filestore
              persistentVolumeClaim:
                claimName: filestore-nfs-pvc
                readOnly: false
          restartPolicy: OnFailure