apiVersion: apps/v1
kind: Deployment
metadata:
  name: at-ai-att-fe-ui
  namespace: advtech
spec:
  replicas: 1
  selector:
    matchLabels:
      app: at-ai-att-fe-ui
  template:
    metadata:
      labels:
        app: at-ai-att-fe-ui
    spec:
      containers:
        - name: at-ai-att-fe-ui
          image: ghcr.io/acspubsedsg/at-ai-att-fe-ui:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: test
          resources:
            requests:
              cpu: 1000m
              memory: 2048Mi
            limits:
              cpu: 1500m
              memory: 3072Mi
          livenessProbe:
            initialDelaySeconds: 30
            periodSeconds: 5
            httpGet:
              path: /transfer/HealthMonitor
              port: 8080
          readinessProbe:
            initialDelaySeconds: 30
            periodSeconds: 5
            httpGet:
              path: /transfer/HealthMonitor
              port: 8080
          volumeMounts:
            - mountPath: /appl/iapps/ssoProperties/
              name: at-ai-att-fe-ui-config-volume
      hostAliases:
        - hostnames:
            - "ssotest.acs.org"
          ip: "45.60.77.135"
      volumes:
        - name: at-ai-att-fe-ui-config-volume
          configMap:
            name: at-ai-att-fe-ui-configmap
      imagePullSecrets:
        - name: ghcr-token-github-com
