apiVersion: apps/v1
kind: Deployment
metadata:
  name: at-manuscript-editor-distribution
  namespace: advtech
spec:
  replicas: 1
  selector:
    matchLabels:
      app: at-manuscript-editor-distribution
  template:
    metadata:
      labels:
        app: at-manuscript-editor-distribution
    spec:
      containers:
      - name: at-manuscript-editor-distribution
        image: ghcr.io/acspubsedsg/at-manuscript-editor-distribution:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: test
        resources:
          requests:
            cpu: 1000m 
            memory: 2048Mi
          limits:
            cpu: 1500m 
            memory: 3072Mi
      #   volumeMounts:
      #   - mountPath: /appl/iapps/ssoProperties/
      #     name: at-manuscript-editor-distribution-config-volume
      # volumes:
      #   - name: at-manuscript-editor-distribution-config-volume
      #     configMap:
      #       name: at-manuscript-editor-distribution-configmap
      imagePullSecrets:
        - name: ghcr-token-github-com  