apiVersion: v1
kind: Service
metadata:
  name: at-resource-monitor-ui
  namespace: advtech
  annotations:
    cloud.google.com/backend-config: '{"ports": {"8080":"at-ai-att-dashboard-backendconfig"}}'
    cloud.google.com/neg: '{"ingress": true}'
  labels:
    app: at-resource-monitor-ui
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: at-resource-monitor-ui
    