apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: hpa-demo-deployment
  namespace: advtech
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: at-ai-att-fe-api
  minReplicas: 1
  maxReplicas: 5
  targetCPUUtilizationPercentage: 75